default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: detective_app_development

test:
  <<: *default
  database: detective_app_test

production:
  <<: *default
  database: detective_app_production
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
